### ISSUE TITLE
Migrate to actions

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_CircuitPython_AT86RF233#1]
Looks like I missed this one with a copy and paste error. Please actionify

**Comment by evaherrada** [comment]
Ok. I added the .github directory. Should I also add a blank setup.py.disabled?

**Comment by evaherrada** [comment]
@siddacious Also, is there a way to run GitHub actions locally to be able to test the whole build.py file at once, versus having to run each command separately when doing local testing

**Comment by siddacious** [comment]
@dherrada good to ask but no, there is no need to add a PyPi disabler as there isn't anything in the repo to risk being deployed ;)

For actions, it's not possible as far as I know to test _locally_ any way, but you can enable actions on your fork and test there. I believe @sommersoft did the same when we were working on the initial setup so perhaps he can advise if it's not immediately obvious. Don't add the secrets to your fork though as you don't want to accidentally push to PyPi.

This is a good idea because in addition to being easier, it's a better test to use the 'real thing' ie: actions rather than trying to replicate it by testing the individual pieces in isolation. Sometimes issues only pop up when the individual pieces interact.
